version: '3.3'

services:
  blogdb:
    container_name: blogdb
    image: mysql:5.7.27
    environment:
      MYSQL_DATABASE: 'blog'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_ROOT_PASSWORD: 'rootpasswd'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '33066:3306'
    expose:
      - '3306'
    volumes:
      - blogdb:/var/lib/mysql

  blogapp:
    container_name: blogapp
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    command: php -S 0.0.0.0:8080 -t public
    depends_on:
      - blogdb
    links:
      - blogdb
    volumes:
      - ../:/var/www/html

volumes:
  blogdb:
